spring:
  application:
    name: zuul
  cloud:
    config:
      override-none: true  
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
        
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  sensitive-headers: 
  retryable: true  #启用重试       默认不启用
  routes:     #访问地址，默认就是下面的这样，从eureka中拉取注册信息
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500  
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
            
